spring:
  profiles:
    active:
      - dev
---
server:
  port: 8203
spring:
  profiles: dev
  application:
    name: cloud-config-client-dev11
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: cloud-config-client-test
